---
# Tower supports only project specific Ansible collections in job runs.
# Tower installs collections in that file in the implicit project sync before a job run
collections:
  - name: community.kubernetes
    source: https://galaxy.ansible.com
    version: 1.1.1
